--- !ruby/object:OpenStruct 
table: 
  :username: twitter
  :email: you@awesomeness.com
  :since: 1379013457
  :address: "smtp.gmail.com"
  :port: 587 
  :domain: "sample@yourdomain.com"
  :user_name: "sample"
  :password:  "samplepassword"
  :authentication:  => :plain
